version: '3'
services:
  app:
    build: .
    image: dhanujak/week5app:1.1.1
    container_name: docker_week5
    ports:
      - '8090:8085'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: on-failure